# Generated by Django 3.2.8 on 2022-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='email_confirm',
            field=models.IntegerField(default='5554'),
        ),
    ]
