# Generated by Django 3.2.8 on 2022-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_usertype_email_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='user_pin',
            field=models.IntegerField(default='5554'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
